server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: "qa"

build:
  version:
    "7.3"

loans:
  message : "Hello This Message is from loans config -->From QA"
  contactDetails:
    name: "Nagarjun--->SDE2"
    email: "nagarjun@gmail.com"
  onCallSupport:
    - 987654321
    - 123456789