build:
  version:
    "7.3"

loans:
  message : "Hello This Message is from loans config -->From QA"
  contactDetails:
    name: "Nagarjun--->SDE2"
    email: "nagarjun@gmail.com"
  onCallSupport:
    - 987654321
    - 123456789